sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: GlUXAIGGkg5cyGmnkRVpCGpd9K9jEaj/gjR5IrmfAT6s4buPOsj4prTUhx4J6IMpx6qGjUr6CofkpSxcs98Rx0+++NoyhHX7ri3QLKgMI0lNCm6qhgBLhV2uZuutVE3XmJTECEy1uicvWP2OPqJx4UeFCG992ZUohqhjyljrn/EmEtTd08W7huF9briPDvNC6WatbnHFUpx7Kuj9Aeo78wEzyjdKdDBkhUZTIWGoMvoTPOniOSvJm5AicxQ4jR2+aoBnwMO7V4j3Coqoftpyf0ZxDZm6KwfS5yCID7L/0OD9VT4RXmhIu3SvzMu4GYHTmRgD7ZYkmHPMXB9dXA3/+WmSXjI/Oa3P1oUa3rro3adgXPYauUaD9qNSYpi+JpzpmUVloI/I0itW6AsXXzCyH+ro6VhuG9mtVOA/D6MHHiw4Tl5fehZCiV027+WQY4opZKQJ77l+Nmnnrmy+CJjaAFnfikUnpUmkUJof7kj1BUHrMMaIRt6KD9jt5KjrlvFfYRCJYuAXGyi+mK2GRqif1ECcZLXU7PKS6+4C0PxHqKCCYFb4UnWpU2diIAZwFE6eWN11xECimQKyjY11L96kma1Ln9T4Rrh05O3YNeXpZG1wCcQQ51zGuWjTWR/gNOeQjoSpEcWLLn8b0+Mjz1BKg/9qPB8ESPgeIjXv1yds3zc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Tea-Table-Talk_2353
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy